### ISSUE TITLE
How the -k option affects SV call results

### ISSUE THREAD

**Issue by jnktsj** [walaj/svaba#11]
Hi Jeremiah,

I was wondering how the `-k` option affects SV call results. When specified, will local assembly results or any other stats derived from input data be affected? Or does the option only affect reporting?

In other words, will the results of the following runs be the same?

1. Run SvABA with `-k ${target.bed}`
2. Run SvABA *without* `-k` and then extract the SV calls overlapping with `${target.bed}`

Thanks!
-Junko

**Comment by walaj** [comment]
Hi Junko,
The results from 1 and 2 should be the same. ``-k`` just limits the places where SvABA runs. Everything else is the same.
-Jeremiah

**Comment by jnktsj** [comment]
Thanks Jeremiah! I'll close this issue.
