### ISSUE TITLE
SvABA not reading regions file

### ISSUE THREAD

**Issue by dannyjomaa** [walaj/svaba#110]
Hi there, I'm running the SvABA workflow on Terra and am getting the following error:

ERROR: Cannot read region file: /cromwell_root/fc-96c3caa0-16a6-445c-b9ed-e9481a11f7e0/regions.bed or something wrong with bam header ('chr' prefix mismatch?)

As input, I'm providing a BED file formatted (with no header) with each chromosome's start and end positions, e.g.:
chr1	  0	249250621
chr2	  0	243199373

Do you know what may be causing the error here? Thanks so much for any ideas you can suggest!

**Comment by walaj** [comment]
Most likely (other than some Terra processing bug that causes it to point
to a non-existent file) is that the BAM you are using has chromosomes
labeled "1", "2" etc, but your BED file is labeled "chr1" etc. SvABA
doesn't know that chr1 and 1 are the same, so it may be that it's not
finding any overlap with your BAM file. Can you look at the header of your
BAM and see how the chromosomes are labeled?

**Comment by dannyjomaa** [comment]
Thanks so much! Apart from downloading the file from Terra, do you know if there's a way that I can check the header to see the chromosome format or otherwise confirm how they're labeled? I can't seem to preview the file and I've tried a few combinations of the labeling that haven't worked (unfortunately each one also takes 2-3 hours to run).

**Comment by walaj** [comment]
You’d have to use something like “samtools view -h” to grab a sample of the BAM to inspect. It’s going to be hard to debug this or any processing issue without access to the BAM file. 

The only other thought is that svaba puts out a *.log file that may probably prints out the chromosomes it sees. You could see if you can inspect that. 

Ideally, best practice would be to have a piece of the BAM available, and run svaba yourself on the command line to make sure it’s doing what you think it is, before batching through Terra.

**Comment by dannyjomaa** [comment]
Okay, thanks again for all your help! I'll try and inspect part of the BAM file or see if I can run SvABA on part of it locally. I haven't been able to locate the *.log file yet but will look into that more as well. Thank you for all the suggestions!
