### ISSUE TITLE
How can I find contig info of "~~01D"?

### ISSUE THREAD

**Issue by hadgie** [walaj/svaba#117]
Hello, I am going through the `alignments.txt` file to search for certain contigs from the `sv.vcf` file. I can easily find the `c_x_xxxxxxxx_xxxxxxx_xxC` contigs, but cannot find the contigs that ends with -01D like `1:4204471(-)-1:4204965(+)__1_4189501_4214501D` . What could be the main difference of these two identifier type, and is there a way to find the contigs matching the `-01D`s?

Thanks in advance.

**Comment by walaj** [comment]
Hello. The SVs of the type you are looking for are "discordant read-only", meaning that there is no contig to find. They are generally lower quality results, depending on the nature of your sequencing data.

**Comment by hadgie** [comment]
I see. Thanks for the reply.
