### ISSUE TITLE
How to input multiple case bams?

### ISSUE THREAD

**Issue by kimin0402** [walaj/svaba#118]
Hi, just a quick question

From the instruction of svaba, it says more than 1 bam file can be given as input for case bam. 

I tried to call somatic SV in multiple bam files with one control bam, so the code was like the following

```
$svaba run -t tumor1.bam,tumor2.bam,tumor3.bam -n normal.bam
```

But svaba throws error. I tried spaced separated, comma separated list of bams, but it didn't work.

How can I fix this?

**Comment by walaj** [comment]
Each gets its own `-t` flag. The idea of the multiple bams in one run is if they are related samples -- e.g. trios or multiple tumors from the same patient. I would not use this from unrelated tumors or patients. The results will be combined across all, and the genotype field will indicate which files have the variant supporting reads.
