### ISSUE TITLE
No SV output with metagenomics data

### ISSUE THREAD

**Issue by wshuai294** [walaj/svaba#119]
Hi,

When I run SVABA with the metagenomics reads alignment to a large microbial reference, I get this error
```
Running region GUT_GENOME286887_234:1-1,697(*) on thread 139746049373952
Running region GUT_GENOME286887_235:1-1,631(*) on thread 139746015811328
        Total of 127 bad mate regions for this thread

Running region GUT_GENOME286887_236:1-1,583(*) on thread 139746116499200
        Total of 127 bad mate regions for this thread

Running region GUT_GENOME286887_237:1-1,533(*) on thread 139745814435584
        Total of 127 bad mate regions for this thread

        Total of 127 bad mate regions for this thread

        Total of 126 bad mate regions for this thread

        Total of 127 bad mate regions for this thread
```
Strangely, sometimes I can run it successfully. Could you please help me with this?

Shuai

**Comment by walaj** [comment]
It looks like it's complaining about "bad mate regions" which is a fail-safe to prevent it from spending too much time looking up mate reads for regions with extremely high read counts (which are artifactual in human data). I think this threshold can be increased with -x parameter. The default is 50000. 

That said, I have no idea how this would work on metagenomics data, or know whether this is the right tool for what you want.
