### ISSUE TITLE
[E::bwa_idx_load_from_disk] fail to locate the index files

### ISSUE THREAD

**Issue by chorong5155** [walaj/svaba#125]
Hi all,
I am a beginner running bwa.. 
I keep running into

[E::bwa_idx_load_from_disk] fail to locate the index files
/var/spool/slurmd/job3476723/slurm_script: line 45: /HapIP_Mock_polysome_19215R-02-03_S67_L002.paired.sam: Permission denied 

These two errors..

below is from the snap of the process..

[BWTIncConstructFromPacked] 680 iterations done. 6184442904 characters processed.
[bwa_index] 2364.60 seconds elapse.
[bwa_index] Update BWT... 14.77 sec
[bwa_index] Pack forward-only FASTA... 13.99 sec
[bwa_index] Construct SA from BWT and Occ... 1000.04 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index /projects/b1042/WalshLab/cpp4747/trial/genomes/hg38+VacV.fna
[main] Real time: 3435.034 sec; CPU: 3415.497 sec
[E::bwa_idx_load_from_disk] fail to locate the index files
/var/spool/slurmd/job3476723/slurm_script: line 45: /HapIP_Mock_polysome_19215R-02-03_S67_L002.paired.sam: Permission denied

I found a few also ran into these issue but could not find the solution for me..
I would much appreciate if you could give me kind advice! 

Thanks

**Comment by walaj** [comment]
Will close since not a svaba problem. Looks like an issue with permissions and indexing, should direct to a local informatician who can help with your computing environment.
