### ISSUE TITLE
"Filed to load index for ..."  error while running SvABA. 

### ISSUE THREAD

**Issue by biotech25** [walaj/svaba#15]
Hi Jeremiah, 

I am testing SvABA but I got an error message about "loading index" and didn't get '.vcf' output files. The command line I used is like below.

svaba run -t ../54_dbGaP_RNA-seq_FusionCapture_BWA/FusionCaptureTest_ReadID_NewFormat_test_20180118/aln_fq_paired_SRR988437_1_200M.fastq.gz.bam **-G ./BWA_Reference_fasta/GRCh38.primary_assembly.genome.fa** -p 16 -D ./DBSNP_knownIndel/dbsnp_indel.vcf -a SRR988437_200M

The log file is attached. If you see the log file, the main error messages are; "Failed to load index for....." and the last line is 

svaba: run_svaba.cpp:1788: CountPair collect_mate_reads(WalkerMap&, const MateRegionVector&, int, SeqLib::GRC&): **Assertion `w.second.SetMultipleRegions(gg)' failed.**
/var/spool/slurmd/job624012/slurm_script: line 20: 15817 Aborted                 svaba run -t /pghbio/dbmi/xwangp/sal170/55_Snowman_54729-5_AIR/2_54729-5_WGS_AIR_BRCA_BAM/aln_fq_paired_SRR476765.bam -G ./BWA_Reference_fasta/GRCh38.primary_assembly.genome.fa -p 16 -D ./DBSNP_knownIndel/dbsnp_indel.vcf -a SRR476765

As I read the SvABA manual again, it says "A BWA-MEM index reference genome must also be supplied with -G"   But, as I see the example command line, "-G" needs refseq fasta file. So, I just used **GRCh38.primary_assembly.genome.fa**.   Should I use BWA-MEM index ref genome with -G?  Then, could you provide the BWA-MEM index ref geneom? 

Thank you, 
Sanghoon

[svaba_tumorOnly_SRR476765.log](https://github.com/walaj/svaba/files/1760228/svaba_tumorOnly_SRR476765.log)

**Comment by walaj** [comment]
Hi Sanghoon,
Is the genome indexed? Try ``bwa index GRCh38.primary_assembly.genome.fa`` and then re-run. The ``-G`` should be to the fasta file, but it has to have the multiple bwa index files.

**Comment by biotech25** [comment]
Thank you for your explanation. Yes, the genome fasta file was bwa indexed. "GRCh38.primary_assembly.genome.fa" is stored with 
- GRCh38.primary_assembly.genome.fa.amb
- GRCh38.primary_assembly.genome.fa.ann
- GRCh38.primary_assembly.genome.fa.bwt
- GRCh38.primary_assembly.genome.fa.fai
- GRCh38.primary_assembly.genome.fa.pac
- GRCh38.primary_assembly.genome.fa.sa

I tested the command below following your advice. Yes, it seems to work. I get '.vcf' files, although the '.vcf' file has just meta-data and empty. (I used just a example fastq file)  I am going to test more with real tumor and normal fastq files.  

svaba run -t ../54_dbGaP_RNA-seq_FusionCapture_BWA/FusionCaptureTest_ReadID_NewFormat_test_20180118/aln_fq_paired_SRR988437_1_200M.fastq.gz.bam **bwa index ./BWA_Reference_fasta/GRCh38.primary_assembly.genome.fa -G ./BWA_Reference_fasta/GRCh38.primary_assembly.genome.fa** -p 16 -D ./DBSNP_knownIndel/dbsnp_indel.vcf -a SRR988437_200M

Thank you for your help!!
Sanghoon

**Comment by biotech25** [comment]
In the log file, I am getting multiple lines of the message below.   Is this okay..?

**Failed to load index for** ../54_dbGaP_RNA-seq_FusionCapture_BWA/FusionCaptureTest_ReadID_NewFormat_test_20180118/aln_fq_paired_SRR988437_1_200M.fastq.gz.bam. Rebuild samtools index

**Comment by walaj** [comment]
Samtools index the bam file.
