### ISSUE TITLE
Splitting input file to small files / Directing output directory

### ISSUE THREAD

**Issue by biotech25** [walaj/svaba#16]
Hi, 

I have two questions. 

1) Splitting input file to small files. 
My input files (bam files) are 100 ~ 130 GB. When I ran svaba first time in a super computer (16 cores multi-thread), I set waltime limit 72 hours, but the running exceeded 72 hours and terminated. I didn't know the running will take this long time.  I wonder if I can split the BAM file to small files, and run svaba. I just googled whether I can split BAM file, and I found some information.;
https://www.biostars.org/p/46327/    Once I can split the BAM file and run svaba for small input files, I think I can get multiple outputs from multiple runnings, and then I can combine the outputs.  Would it be okay? 

2) Directing output directory. 
I tried to direct output directory. So, I tried to see if there is a flag that can enable to direct output files, but it seems not. "-a" is just output file name prefix.  Does svaba has a flag that can direct output files?

Thank you, 
Sanghoon

**Comment by walaj** [comment]
Hi Sanghoon,
1) I would not split the BAM. It will be a headache for little to no gain. The speed issues are likely due to I/O and depending on the speed of you file system, running 16 cores may end up slowing you down. 
2) Just run SvABA from the directory you want to output the files to.

**Comment by biotech25** [comment]
Thank you, Jeremiah, for your kind explanation!! Your answer is helping me a lot. 

Sanghoon
