### ISSUE TITLE
Tumor only analysis

### ISSUE THREAD

**Issue by CarlosBorroto** [walaj/svaba#17]
Hi @walaj,

I'm trying out svaba for the first time looking to call somatic mutations on tumor only data. I was wondering if there is a recommended way to run svaba in those cases?

Thanks,
Carlos

**Comment by walaj** [comment]
Hi Carlos, 
You don’t technically need to have a matched normal to run, just run with -t for the BAM. You’ll still have to have a way, outside SvABA, to filter germline events. You can also use the -V option to mark within SvABA germline CNVs, if you have a BED file of germline CNVs. In general though, it is a challenge not having the matched normal.

**Comment by CarlosBorroto** [comment]
Thanks for the pointers. I'll give this a try.
