### ISSUE TITLE
Multi-threading not working

### ISSUE THREAD

**Issue by anso-sertier** [walaj/svaba#19]
Hello,
I've installed svABA with gcc 4.9.2 on centos 6.2
If I run without -p option, I got:
```
-----------------------------------------------------------
--- Running svaba SV and indel detection on 1 threads ---
---    (inspect *.log for real-time progress updates)   ---
-----------------------------------------------------------
[M::bwa_idx_load_from_disk] read 0 ALT contigs
--- Loaded non-read data. Starting detection pipeline
 Caught exception for lregion with reg 1:1-25,001(*)
Caught exception in BreakPoint:setRefAlt for indel ref: RefGenome::queryRegion - Returning empty query on 1:10396-10402
Caught exception in BreakPoint:setRefAlt for indel ref: RefGenome::queryRegion - Returning empty query on 1:10402-10439
Caught exception in BreakPoint:setRefAlt for indel ref: RefGenome::queryRegion - Returning empty query on 1:10408-10439
...
```

but with -p 8 option, program fails :

```
-----------------------------------------------------------
--- Running svaba SV and indel detection on 4 threads ---
---    (inspect *.log for real-time progress updates)   ---
-----------------------------------------------------------
[M::bwa_idx_load_from_disk] read 0 ALT contigs
--- Loaded non-read data. Starting detection pipeline
 Caught exception for lregion with reg 1:49,001-74,001(*)
Floating point exception
```

Do you have any idea of the problem's origin ?
I've attached log files of configure and make commands if it can help.

Thanks in advance for any help !

Anne-Sophie

[svaba_config.log](https://github.com/walaj/svaba/files/1863227/svaba_config.log)
[svaba_install.log](https://github.com/walaj/svaba/files/1863228/svaba_install.log)

**Comment by walaj** [comment]
Hi Anne-Sophie,
This is definitely not the expected behavior! I think this may be related to a mismatch between the reference genome that you are aligning too and the one used within SvABA. Can you check that the chromosomes defined in the header of the BAM are the same (e.g. either have "chr" prepended or don't) as the one in your reference genome?
Best,
Jeremiah

**Comment by anso-sertier** [comment]
Hi Jeremiah,
Thanks for your answer. I was out of my office last weeks... Chromosome definition is the same between my bam file and the reference genome I supply to svABA. However, I ran svABA on 1 cpu as it did not crash. I obtained results in the VCF file (sv and indels) but alt and ref are all "N", or repeat of N in the indel vcf, see next examples 

> 1       161121072       50092:1 N       N[1:161121257[  12      PASS    EVDNC=ASSMB;HOMSEQ=TGCAGTG;MAPQ=60;MATEID=50092:2;MATENM=0;NM=0;NUMPARTS=2;SCTG=c_1_161112001_161137001_24C;SPAN=185;SUBN=1;SVTYPE=BND  GT:AD:DP:GQ:PL:SR:DR:LR:LO      0/0:0:14:3.6:0,3.6,39.6:0:0:3.88:0      0/1:7:37:12.8:12.8,0,78.8:7:0:-12.85:15.6
> 1       161121257       50092:2 N       ]1:161121072]N  12      PASS    EVDNC=ASSMB;HOMSEQ=TGCAGTG;MAPQ=60;MATEID=50092:1;MATENM=0;NM=0;NUMPARTS=2;SCTG=c_1_161112001_161137001_24C;SPAN=185;SVTYPE=BND GT:AD:DP:GQ:PL:SR:DR:LR:LO      0/0:0:14:3.6:0,3.6,39.6:0:0:3.88:0      0/1:7:37:12.8:12.8,0,78.8:7:0:-12.85:15.6

Thus I agree with a problem with the reference ...
I can visualize alignments on IGV from the outfile P03023.contigs.bam at positions given in VCF, and they seem ok. I suspect something : I do not redo the index of my reference as I had once done with bwa-0.7.15
Do I need to rebuild index with the bwa version installed with svABA (or tell svABA to use "my" bwa program) ?

Thanks a lot for your help !

Best,
Anne-Sophie

**Comment by walaj** [comment]
Hi Anne-Sophia,
I'm not sure what is going on. I doubt that rebuilding with a different
version of bwa would make a difference. Can you view the reference in IGV?
I think I'd need a MWE to really debug this.

**Comment by anso-sertier** [comment]
Hi Jeremiah,
i've created small bam (chrom 1 until pos 18,000,000) and run svABA with 1 and 8 cpu
(p1 and p8 subfolders in zip file)
you can find input bam and all outputs here :

https://www.dropbox.com/sh/belbd5mm4pe00wk/AACluT94vUCBedgbZZpRiVNpa?dl=0

I used b37 ref genome, tell me if you need more informations

Thanks a lot in advance for your help
Anne-Sophie

**Comment by walaj** [comment]
Thanks for posting these. I ran svaba on this (including multi-core) and had no problems. The variants have proper ATCG bases (not Ns). Perhaps also posting your reference genome would be needed to recreate?

**Comment by anso-sertier** [comment]
I have added the reference genome used in the dropbox folder
I really don't understand what’s wrong …
thanks for your help !!

Le 24 avr. 2018 à 18:27, Jeremiah Wala <notifications@github.com<mailto:notifications@github.com>> a écrit :


Thanks for posting these. I ran svaba on this (including multi-core) and had no problems. The variants have proper ATCG bases (not Ns). Perhaps also posting your reference genome would be needed to recreate?

**Comment by walaj** [comment]
I'm still not able to re-create with the reference you provide. 

I do, however, think that the issue may actually be in the index that samtools creates, not the one bwa creates. Each is based on the FASTA file, but the samtools index is used to extract sequences from the reference. If this fails, it would give N's in SvABA. Can you try indexing also with samtools. e.g. ``samtools faidx human_g1k_v37.fasta``?
