### ISSUE TITLE
Parameter for limitation of Weired read

### ISSUE THREAD

**Issue by sgilab** [walaj/svaba#23]
Hi Jeremiah,

I am trying to apply SvABA to high depth targeted panel data (~1000X), especially highly fragmented FFPE tissue. Due to the numerous split reads of FFPE, SvABA printed out these messages when it ran.

breaking at 2:11,166,812(-) in window 2:11,166,378-11,167,271(*) with 401 weird reads. Limit: 400 breaking at 2:11,171,138(-) in window 2:11,170,834-11,171,424(*) with 401 weird reads. Limit: 400 breaking at 2:11,173,008(+) in window 2:11,172,546-11,173,220(*) with 401 weird reads. Limit: 400
.
.

I could not find the proper parameter to optimize these issues. How I optimize SvABA for FFPE samples with many weird reads? and does SvABA have any problems running without control data?

Thanks

Hyun-Tae

**Comment by walaj** [comment]
Hi Hyun-Tae, 

Good point. The issue with the coverage should be modifiable with a command line parameter, although I think now they are hard-coded. I can provide an update soon that allows for turning off these limits. Should only take a few minutes once I get to my computer. 

There is no issue without a control. You just won’t be able to call tumor v normal. 

Best, 
Jeremiah

**Comment by sgilab** [comment]
Thank you for updating the parameters for my answer. I will test with the changed parameters.
