### ISSUE TITLE
LOH detection

### ISSUE THREAD

**Issue by paprikachan** [walaj/svaba#31]
Hi @walaj ,

Can I get the LOH result from svaba? Thanks.

**Comment by walaj** [comment]
Not explicitly. To call LOH you want to see a string of het sites that become homozygous, which really requires SNV calling. There are tools that do LOH detection from SNVs (I am thinking of ABSOLUTE or ASCAT). If you wanted to see the breakpoints for the event that led to LOH, SvABA can do that.
