### ISSUE TITLE
Reads supporting Variant call

### ISSUE THREAD

**Issue by pwanj** [walaj/svaba#33]
Hello,

Please can you tell me how to get information about number of reads supporting the variant listed in the *sv.vcf output file?

I would really appreciate it. Thanks!

**Comment by walaj** [comment]
This information is listed in the Genotype field of the VCF. The genotype field will give the total coverage, supporting reads (broken down by split, discordant) for each sample. Note that, as outlined in prior issue reports, that for SVs the number of ALT reads can be greater than the total coverage, and that the number of split + discordant reads does not need to equal the ALT count, owing to some reads being _both_ split and discordant.

**Comment by pwanj** [comment]
Thank you for getting back to me. 

I have one more question. Please can you tell me how the QUAL scores in the output VCF files (*sv.vcf) calculated?

**Comment by walaj** [comment]
The QUAL score is the log-odds that a variant is non-homozygous reference, given the number of REF and ALT reads. It is calculated in ``__genotype_likelhoods`` and based on the equation from http://bioinformatics.oxfordjournals.org/content/early/2011/09/08/bioinformatics.btr509.full.pdf+html. 

Note that, as in most all variant callers, the QUAL captures some error modes but not all. However, it is very useful for filtering variants with low read support.

**Comment by pwanj** [comment]
Thank you for the information. I really appreciate it.
