### ISSUE TITLE
Example dbsnp_indel.vcf no longer available 

### ISSUE THREAD

**Issue by ipstone** [walaj/svaba#35]
The example dbsnp_indel.vcf is no longer available:  `wget "https://data.broadinstitute.org/snowman/dbsnp_indel.vcf" ## get a DBSNP known indel file` 

Is this known indel dbsnp available to download somewhere else? Thanks!

**Comment by walaj** [comment]
Thanks for letting me know. My directories got moved and it looks like my symbolic links went down. I've restored it.

**Comment by ipstone** [comment]
Awesome!

**Comment by Mingxi-HUANG-Sunnia** [comment]
<img width="614" height="181" alt="Image" src="https://github.com/user-attachments/assets/8b0a3b9e-d2bd-4f6c-a809-4954a688f0ee" />

The example dbsnp_indel.vcf is not available again. Is this available for download elsewhere? Thanks!
