### ISSUE TITLE
Compiling v0.2.1 (bioconda recipe)

### ISSUE THREAD

**Issue by micknudsen** [walaj/svaba#43]
I am trying to make a bioconda recipe for SvABA v0.2.1, but I keep getting compiler errors: 

https://github.com/bioconda/bioconda-recipes/pull/12943

The errors are reproducible when I do the compilation locally. However, if I check out the current master branch, everthing works fine. Do you have any plans of making a new release incorporating the latest changes?

**Comment by walaj** [comment]
Hi Mick,
Thanks for your patience and for putting this together. Would be fantastic to have a bioconda recipe for SvABA. I completely agree - this needs a stable release. I finally have some time to work through some of the Issues here, and will flag a release very soon.

**Comment by micknudsen** [comment]
Hi,

I am still trying to make a recipe work on bioconda (now with version 1.1.0, which compiles without any problems locally). However, I run into problems:

```
/opt/conda/conda-bld/svaba_1553869130392/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../../SeqLib/fermi-lite/libfml.a(f_ksw.o): relocation R_X86_64_32 against symbol `f_ksw_u8' can not be used when making a PIE object; recompile with -fPIC

/opt/conda/conda-bld/svaba_1553869130392/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: final link failed: nonrepresentable section on output

collect2: error: ld returned 1 exit status
```

Do you have any clue how to fix this? It may be trivial, but I am not familiar with C/C++ at all, so I am doing this more or less blindfolded. I have tried running

`make -fPIC`

but then I just get:

```
make: PIC: No such file or directory
make: *** No rule to make target `PIC'.  Stop.
```

Thanks!

**Comment by walaj** [comment]
You'll need to tell the compiler where to put the -fPIC flag. I believe either ``./configure CXXFLAGS=-fPIC`` of ``make CXXFLAGS=-fPIC`` will work. Should produce below:

``g++ -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare  -g -Wall -Wextra  -Wno-unknown-pragmas -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -MT libseqlib_a-ReadFilter.o -MD -MP -MF .deps/libseqlib_a-ReadFilter.Tpo -c -o libseqlib_a-ReadFilter.o `test -f 'ReadFilter.cpp' || echo './'`ReadFilter.cpp``

**Comment by micknudsen** [comment]
Thanks! That solved the problem and got me a bit further.
