### ISSUE TITLE
LOWMATCHLEN is a FILTER value in sv.vcf but not described in header

### ISSUE THREAD

**Issue by akell2** [walaj/svaba#44]
There is no description of the LOWMATCHLEN included in the vcf header. Lines 738-741 in BreakPoint.cpp define the criteria for this FILTER value, but then a description is missing for LOWMATCHLEN in the sv_header.addFilterField function within vcf.cpp. This causes errors for bcftools:[W::vcf_parse] FILTER 'LOWMATCHLEN' is not defined in the header
Error: The filter is not defined in the header: LOWMATCHLEN

**Comment by walaj** [comment]
Thanks for catching this. This should now be fixed.
