### ISSUE TITLE
Strange output with in-house reference

### ISSUE THREAD

**Issue by yiqijiang17** [walaj/svaba#45]
Hi,
I try to use svaba to detect bacterial SVs in metagenomics data with a reference contains ~600 bacterial genomes. And in *discordant.txt.gz output, I notice the chromosome id 'chr1' and 'chr2' are range from 1 to 24; while in *.alignments.txt.gz output, BP information had some chromosomes named 'X', 'Y' and 'M', like: 
Global BP: : X:2,968,914(+) to 457:3,952,360(-) 
...
Global BP: : Y:349,942(-) to 104:1,266,871(-)
...
Global BP: : M:10,276(+) to 552:23,800(-)
which are not in my reference.

I guess this may caused by svaba treated the reference as human genome. 
Is it caused by that? and if there any way I can do to make svaba can used with this reference?

Thanks a lot!

**Comment by walaj** [comment]
Good catch -- I had thought I removed any hard-coded references to the human genome, but they persisted as shortcuts in the print functions (it was assuming chr with numeric id 23 was "X"). 

I made branch ``i47`` with changes to fix this. Can you re-run using code from this branch (do a full checkout with the updates submodule ``SeqLib`` as well)?

**Comment by yiqijiang17** [comment]
Hi Jeremiah,
I re-run with `i47` branch, and it works well!
Only one suggestion, in *discordant.txt.gz output, all chr names are replaced by numeric number based on reference order, which needs users to change them back by own script to match names in other output files.

Example:
reference:
>\>NC_XXXX
>...
>\>NC_YYYY
>...


in *discordant.txt.gz:
>chr1 ... chr2 ...
>1 ... 2 ...

in *sv.vcf:
>NC_XXXX ...

Names in vcf and discordant.txt can't match.


Really thanks for your help!

Yiqi

**Comment by walaj** [comment]
Thank you for finding this as well. I fixed this issue and merged your suggested changes into the master branch.
