### ISSUE TITLE
a question about TSI?

### ISSUE THREAD

**Issue by wisekh6** [walaj/svaba#49]
Hi Walaj,

I wonder if you can give more explanation on TSI_L and TSI_G in the "bpx.txt".
The VCF file says:
``` 
TSI_L templated-sequence insertion (local, e.g. AB or BC of an ABC), TSI_G global (e.g. AC of ABC)
```
Here, could you more clarify what "AB, BC, AC, ABC" represents?
I guess that **ABC** means an assembled sequence is aligned onto three pieces (A-B-C), and the bp pairs (pos1 and pos2) represent AB, BC, or BC. Is this a correct interpretation?

Thank you in advance,

**Comment by walaj** [comment]
Thank you for your patience with this. I think your interpretation is correct. Considering a contig with three alignments to the reference, indicating a templated-sequence insertion:

|---A---|---B---|---C---|      (for example, part "A" maps to chr1, "B" to chr2, "C" to chr10).

TSI_L is a "templated-sequence insertion" describing a "local" connection, so will report A-B and B-C.

TSI_G is the "global" version of above, which alternatively reports the A-C connection. Depending on what a user is interested in, one way or the other of representing these TSI events will be more useful. I therefore provide both.
