### ISSUE TITLE
Invalid VCF output

### ISSUE THREAD

**Issue by CliffordWollam** [walaj/svaba#58]
It looks like you made changes between your 1.0.1 and 1.1.0 releases that caused invalid VCF output. The problem is that in the data portion there are now 3 extra columns:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  XXXX.bam
CHR1       6913559 152101861       G       GA      2       MULTIMATCH      LOD=2.602;MAPQ=43;NM=6;REPSEQ=AAGAAG;SCTG=c_1_6909001_6934001_0C;SPAN=1 GT:AD:DP:GQ:PL:SR:CR:LR:LO      2       2       2       1/1:2:2:0.2:2.6,0.2,0:2:2:-2.602:2.602
```

Note the "2 2 2" between the FORMAT and XXXX.bam columns.

**Comment by walaj** [comment]
Thank you for catching this -- just pushed a patch.

**Comment by micknudsen** [comment]
@walaj Do you plan to make a new release with this fix at some point?

**Comment by walaj** [comment]
@Manuelaio What is the error you are getting with PySam? Are you seeing the same issue with extra fields? That should have been fixed with the patch above.
