### ISSUE TITLE
[ERROR] svaba-annotate.R: Unknown column 'name2' in 'field list'

### ISSUE THREAD

**Issue by chunyangbao** [walaj/svaba#59]
I got the following ERROR when I ran svaba-annotate.R
Error in .local(conn, statement, ...) : 
  could not run statement: Unknown column 'name2' in 'field list'

Please help me to take a look at L60:
  genes <- suppressWarnings(data.table::as.data.table(query(paste0("SELECT name, name2, chrom, txStart, txEnd, strand, exonStarts, exonEnds, exonCount FROM ", assembly, ".knownGene"))))  

Thanks,
Chunyang

**Comment by chunyangbao** [comment]
It seems that 'knownGene' does not have 'name2'.  I used 'refgene' instead...

**Comment by walaj** [comment]
Thanks for finding this. I removed ``name2`` from the gencode db query.
