### ISSUE TITLE
Error with simulated data

### ISSUE THREAD

**Issue by gunjangala** [walaj/svaba#6]
Hi Walaj,

I am working with some simulated paired-end data generated using wgsim (coverage=100X, read length=70bp, mean insert size=150 and sd insert size=15). When I run svaba, I come across the following errors:

`!!!! WARNING. Multiple max mapq mixed: NC_001137.3_164083_164206_2--60 max possible 60`
```
not enough paired-end reads to get insert-size distribution. skipping discordant analysis
       tead group: NC_001136.10_331155_331313_1 Insert-sizes sampled: 1 visited 2
```
```
 [M::bwa_idx_load_from_disk] read 0 ALT contigs
         --- Loaded non-read data. Starting detection pipeline
```

Also, no output files are generated. Trying the following commands:
```
module load svaba/intel/20170210 
svaba run -p 16 -G $ref -t $bam1
```
Can you help me figure out what could be going on and how to fix it? Also, let me know if you require any additional information.

Thanks,
Gunjan

**Comment by walaj** [comment]
Hi Gunjan,

Thanks for letting me know about this, and I think something is amiss with how SvABA is expecting the format of the simulated reads. Could you attach / send me via email (jwala@broadinstitute.org) a small BAM with this simulated data (e.g. samtools view -h sim.bam | head -n 10000 | samtools view - -hb > min.bam)? I can take a look at give more guidance.

Best,
Jeremiah

**Comment by gunjangala** [comment]
Hi Jeremiah,

Please find the attached .zip file. 

Thanks,
Gunjan

[min.bam.zip](https://github.com/walaj/svaba/files/870907/min.bam.zip)

**Comment by walaj** [comment]
Hi Gunjan,

Regarding the warning you were seeing, there are no read group tags (RG) in this, so it was trying to guess the read-group from the read-name but encountering an unexpected format (e.g. not Illumina). This RG guessing perhaps should be turned off, but another way would be to explicitly provide a RG for each read. 

The BAM you sent was query-name sorted, but I assume you are running this on a coordinate-sorted and indexed BAM.

I also noticed this is being applied to yeast data. If you had the full simulated BAMs and reference genome available on an FTP, I would be interested in downloading and trying on this data. I haven't tried SvABA on non-human data, and would like to make sure the code is robust to non-human data. Should be a quick adjustment.

Thank you again for reporting this issue, looking forward to seeing this work on non-human data.

Best,
Jeremiah

**Comment by gunjangala** [comment]
Hi Jeremiah,

Yes, I am running SvABA on sorted and indexed BAM. Providing RG tag for each read worked and SvABA ran as expected though it did not pick up any simulated variants. I have shared the files with you via Google drive. Please check your email for the same.

Thanks,
Gunjan

**Comment by walaj** [comment]
Closing, per our email thread...
