### ISSUE TITLE
[ERROR] svaba-annotate.R can not read vcf.gz

### ISSUE THREAD

**Issue by chunyangbao** [walaj/svaba#60]
Compressed VCF file can not be processed by svaba-annotate.R

It would be much better if the following line could be updated.
vcf <- data.table::fread(cmd=paste("grep -v ^#", opt$input))

Thanks,
Chunyang

**Comment by chunyangbao** [comment]
Since fread can automatically read compressed file, my naive solution is:
vcf <- data.table::fread(opt$input, skip="#CHROM")

**Comment by walaj** [comment]
Good point. Updated.
