### ISSUE TITLE
Can not install svaba

### ISSUE THREAD

**Issue by shishuo16** [walaj/svaba#65]
Hi Jeremiah,
I have tried many times on different computers. I just counld not install svaba.
When I run "./configure", it stoped with the following info.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/p200/pmod_group/shishuo/software/svaba-master/missing: Unknown `--is-lightweight' option
Try `/p200/pmod_group/shishuo/software/svaba-master/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for library containing gzopen... -lz
checking for library containing clock_gettime... -lrt
checking google/sparse_hash_set usability... no
checking google/sparse_hash_set presence... no
checking for google/sparse_hash_set... no
checking google/sparse_hash_map usability... no
checking google/sparse_hash_map presence... no
checking for google/sparse_hash_map... no
checking unordered_map usability... no
checking unordered_map presence... no
checking for unordered_map... no
checking tr1/unordered_map usability... yes
checking tr1/unordered_map presence... yes
checking for tr1/unordered_map... yes
checking ext/hash_map usability... yes
checking ext/hash_map presence... yes
checking for ext/hash_map... yes
checking unordered_set usability... no
checking unordered_set presence... no
checking for unordered_set... no
checking tr1/unordered_set usability... yes
checking tr1/unordered_set presence... yes
checking for tr1/unordered_set... yes
checking ext/hash_set usability... yes
checking ext/hash_set presence... yes
checking for ext/hash_set... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `SeqLib/src/Makefile.in'

Best,
Shuo

**Comment by walaj** [comment]
Are you cloning with —recursive flag? This is required.

**Comment by shishuo16** [comment]
My mistake. I added recursive flag and it worked well. Thanks so much for the help. And sorry for my mistake. 
    
        
            
                
                    
                        
                    
                    
                        
                            chishuo16
                            
                            
                                
                                    邮箱：chishuo16@sina.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
            On 05/03/2019 19:32, Jeremiah Wala wrote: Are you cloning with —recursive flag? This is required. 



> On May 3, 2019, at 5:14 AM, Shuo Shi <notifications@github.com> wrote:

> 

> Closed #65.

> 

> —

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly, view it on GitHub, or mute the thread.





—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/walaj/svaba/issues/65#issuecomment-489065598",

"url": "https://github.com/walaj/svaba/issues/65#issuecomment-489065598",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
