### ISSUE TITLE
SvABA fails if BED lines too long

### ISSUE THREAD

**Issue by fgvieira** [walaj/svaba#66]
I have been getting an error on `SvABA`:
```
Found chromosome in region file WWW.bed not in reference genome. Skipping.
     Caught error: stoi
ERROR: Cannot read region file: WWW.bed or something wrong with bam header ('chr' prefix mismatch?)
```

and it seems it is because of very long lines on the BED file. In my case, it was the forth column (name) that was giving the error.
Would it be possible for `SvABA` to read the full line but ignore everything after the third tab?

**Comment by walaj** [comment]
Hmm, it would have to be quite long but yes this is possible. SeqLib (which reads the BED in svaba) currently has a max line of ~65k characters. If this is indeed the problem, could you try increasing the variable ``GZBUFFER`` in [this file](https://github.com/walaj/SeqLib/blob/master/SeqLib/GenomicRegionCollection.cpp) and recompiling and trying again?

**Comment by fgvieira** [comment]
Yes, on this BED file I have lines as long as 150k characters.
I am running it on a shared cluster, where I do not have `sudo` rights, but I'll see if I can compile it...

**Comment by walaj** [comment]
OK great, sounds like just upping the GZBUFFER will fix it. You shouldn't
need sudo to compile, you can just compile locally. I'll close this issue,
but let me know if the suggested fix doesn't work.
