### ISSUE TITLE
Chromosome name is 23 assertion error

### ISSUE THREAD

**Issue by kgori** [walaj/svaba#7]
Hi @walaj. I've encountered a problem when running svaba on non-human samples, namely that the program exits with an assertion error when it finds a breakpoint on chromosome 23:

    svaba: BreakPoint.cpp:600: BreakEnd::BreakEnd(const SeqLib::BamRecord&): Assertion `chr_name != "23"' failed.

My samples are dog samples, mapped to CanFam3.1, so they have 38 chromosomes (+ X). What is the quickest way for me to get around this problem?

Thanks,
Kevin

**Comment by walaj** [comment]
Hi Kevin,
This was a hold-over from debugging. I just removed this ``assert`` statement in the latest commit. You can do a ``git pull`` and rebuild.
Let me know if still not working.
-Jeremiah

**Comment by kgori** [comment]
Hi Jeremiah,
I changed the statement to `assert(chr_name != "39");` and it is running fine. This was before I saw your fix. I also changed this in svabautils/splitcounter.cpp, line 160: 

    if (r.ChrID() > 23)
        break;
to 39, just in case that made a difference.

Thanks,
Kevin

**Comment by kgori** [comment]
Hi,
Just wanted to confirm that the analysis worked, except that for one sample every entry in each VCF file was

    0/0:0:0:99:0,0,0:0:0:0:0

I had 15 normal and 17 tumour samples. Did I hit an upper limit on number of samples? There is nothing wrong with that particular file as far as I can tell.

Thanks,
Kevin
