### ISSUE TITLE
The dbsnp_indel.vcf for hg19 genome?

### ISSUE THREAD

**Issue by Chitanda-Satou** [walaj/svaba#74]
Dear all, 

I have download the 
>"https://data.broadinstitute.org/snowman/dbsnp_indel.vcf" ## get a DBSNP known indel file
file, and found it was based on genome b37.

Liftover it to hg19, will lose 184 thousands of the variants, just as:
>7634205  dbsnp_indel.hg19.vcf
>184486    dbsnp_indel.rejected.vcf
>7818519  dbsnp_indel.vcf

Does this matter? Or do you have any suggestion on another resources to use?

Thanks a lot!

**Comment by walaj** [comment]
No changes to above plan -- not worried about the lost variants, it's expected when doing a liftOver like this. Would have done the same as you did above!
