### ISSUE TITLE
Issue with DiscordantCluster.cpp

### ISSUE THREAD

**Issue by MaximilianStammnitz** [walaj/svaba#78]
Hi Jeremiah @walaj,

I am currently comparing SvABA's outputs on the same set of case-controls aligned to a previous vs. new (high-quality) genome assembly.

As before, SV/indel calling runs smoothly on the old reference, however on the newer assembly I regularly obtain the following error message and subsequential run abortions:

"...discordant read clustering
svaba: DiscordantCluster.cpp:306: DiscordantCluster::DiscordantCluster(const svabaReadVector&, const svabaReadVector&, int): Assertion `m_reg2.Width() < 5000' failed."

I couldn't quite figure it out from your DiscordantCluster.cpp function: what is it that triggers the script to break? It reads a bit like this might be related to the insert size of these libraries? 

Wondering if you have come across this before and/or if there's a quick fix to this. I'm happy to provide more log information if needed to check. Thanks a million for your help!

Cheers,
Max

**Comment by MaximilianStammnitz** [comment]
Hi Jeremiah,

Would you mind having a quick look at this, just to see if it can be fixed quickly or if it would require some major time effort?

Many thanks,
Max

**Comment by MaximilianStammnitz** [comment]
Attaching you a typical log file for this problem, which comes up in all tested versions (v0.2.1, 1.0.1, 1.1.0).

[2020-02-07_SvABA_1.1.0.log](https://github.com/walaj/svaba/files/4168450/2020-02-07_SvABA_1.1.0.log)

**Comment by walaj** [comment]
Hi Max,

Thank you for your careful description and significant patience. I’m thinking about what could be happening but don’t have a full explanation at the moment. The insert size distribution shown in the log file is very typical and shouldn’t be breaking this (well really any distribution shouldn’t break this). 

What the error is saying is that SvABA is seeing a mate region that is larger than 5000 bp, which in itself shouldn’t be a problem, so I think that ultimately the “assert” statement may be too strong of a stop here. 

Depending on your familiarity with C++, would you be able to comment out this assert statement, and replace it with a “print” type statement that prints the Width if > 5000? (And recompile). Then we could see what size “mate regions” this is failing on. Have a low threshold to let me know if above code-tinkering doesn’t make sense, I can make a branch for this, just need to get to do so when I get to a computer.

**Comment by MaximilianStammnitz** [comment]
Hi Jeremiah,

Thanks for your help, and good news: the issue can be fixed rather simply!

I realised it all comes down to the initial line:
#define REGPOS1 500000000

This value is currently set to 500 Mb by default, which is large enough to surpass the length of any human chromosome (max. ~250 Mb) but not necessarily sufficient for scaffolds of other (high-q) species assemblies; esp. thinking of some marsupial and also plant references here. 

For the next SvABA release, it would probably be best not to hard-code REGPOS1 and:
1. either let users specify their target organism's largest chromosome size, and round that up to the nearest 100 Mb
2. or fetch the information directly from the fasta index file of the supplied reference genome (although then also need to ask users to create/locate/name in the correct way)

It means that the error message (e.g. "Assertion `m_reg2.Width() < 5000' failed") is slightly misleading, as the issue lies further upstream. Probably the script breaks down at calculating widths reaching beyond the specified REGPOS1. Attaching you a new example log file, this time with REGPOS1 = 800 Mb and print statements for the m_reg1.Width and m_reg2.Width values (which all appear within reasonable ranges).

One question worth discussing: what is the downside of increasing REGPOS1? Does it lead to increased RAM usage, or could it possibly also cause complications with the actual SV calls?

Many thanks again for your support,
Max

[2020-02-15_SvABA_1.1.3-dev.log](https://github.com/walaj/svaba/files/4208465/2020-02-15_SvABA_1.1.3-dev.log)

**Comment by walaj** [comment]
Ah hah! Excellent detective work Max! Thank you so much for doing the lion's share of this bug fix. 

Actually, I realize looking at this that REGPOS1 is just a dummy "max" value, so really the solution is to get rid of it and just replace with "INT_MAX". I suppose this would then just move the issue to problems "chromosomes" longer than 2^31 (~2 billion). I can't go higher than that without switching ``int32_t`` to ``int64_t``, which I'll hold on for now.

Thanks again,
Jeremiah

**Comment by MaximilianStammnitz** [comment]
Great stuff, sounds like using INT_MAX is unlikely to cause any downstream trouble. In hindsight, I should have been less afraid of checking the code in more detail before sending you all those messages; just never did C++ stuff before and prob. would have not been able to fix it beyond variable assignments ...

... will be very happy to continue promoting SvABA in the large-chromosome-non-model-organism world then! :-)
