### ISSUE TITLE
SvABA on 10X data

### ISSUE THREAD

**Issue by mzwaig** [walaj/svaba#80]
Hi Jeremiah,

I ran SvABA on my 10X data, aligned using their barcode-aware aligner. 
I know SvABA is meant for standard WGS but it managed to pull out the barcode tags which support the SVs. 

My question is does SvABA take into account the linked-read barcodes or is it a fluke that they are returned in the output.

Thanks,
Melissa

**Comment by walaj** [comment]
Hi Melissa,
It does track BX tags! It should report the number of supporting tags. I haven't extensively incorporated 10X capabilities into svaba, but this is something that it does track and report.
(will close unless further issues).
Best,
Jeremiah

**Comment by theshowmustgolangon** [comment]
@mzwaig Hi, I am wondering which aligner did you use? I want to take the exact same steps for using svaba, but I am searching for aligner. I am not sure I can use longranger's output yet..!
Thanks.

**Comment by mzwaig** [comment]
I used the LongRanger output/BAM

**Comment by walaj** [comment]
svaba has BWA-MEM baked into it, which it uses for re-realignment and
contig-to-genome alignment.

svaba will also track 10X read support and report it in the genotype field.
You may have to let it know you want this. If you do svaba run —help there
should be an option for tracking BX tags.

**Comment by theshowmustgolangon** [comment]
@walaj  @mzwaig  Thank you so much for you all!

**Comment by theshowmustgolangon** [comment]
@walaj Hi, I have a few questions!
firstly, the option tracking BX tags is --read-tracking Output options? 
And I am curious I can use gap file of my genome assembly for blacklist option.

Thank you so much for the great tool!

**Comment by walaj** [comment]
Reviewing the code again, the tracking of BX tags happens by default. You
shouldn't have to add a flag, that was my mis-remembering how this was
configured.

The --read-tracking will print out the QNAMES of all supporting reads,
which greatly expands the size of the output files and mostly useful for
targeted runs or debugging. It is a separate feature from BX tags.

The blacklist file is used to skip very repetitive areas where reads are
aligned but unlikely to give a meaningful result (while also bogging down
the caller). If there is a gap in the assembly, reads shouldn't be aligned
there anyway so this wouldn't do much I believe. One strategy to make a
blacklist file is to exclude areas with wildly high genome coverage, like
50x + the mean coverage -- these are often found at centromeres etc.

**Comment by theshowmustgolangon** [comment]
@walaj Thank you for your great advice and and the tool. I really appreciate your support and help!!
