### ISSUE TITLE
Does -D option of svaba run requires dbSNP indels vcf or it compatible to any vcf file

### ISSUE THREAD

**Issue by hsiaoyi0504** [walaj/svaba#88]
Dear Walaj,

Thank you for contributing such a great tool. Here, I have question about the `-D` option of svaba run. Does -D option of svaba run requires dbSNP indels? Or, it's compatible to any vcf file. I am asking this because I am thinking if I can just replace that vcf with a customized one.

**Comment by hsiaoyi0504** [comment]
Also, can I just replace it with the vcf contains all kinds of SVs (indels, medium, and large SVs)?

**Comment by walaj** [comment]
It will be able to read any VCF. I can't say I've tested with a VCF that
has large SVs, but it shouldn't be an issue.

**Comment by hsiaoyi0504** [comment]
Thanks. I will report any problem if I do meet one.
