### ISSUE TITLE
[E::hts_open_format] fail to open file

### ISSUE THREAD

**Issue by rmurphy49** [walaj/svaba#9]
Hello,

I'm sure this is something small and insignificant but I am trying to run SvABA for the first time and the following command gives me the following error return:

svaba/bin/svaba run -t /mnt/scratch/users/40057929/MCLHighNov2016/Batch1/04-0309-01-36351377/04-0309-01_S2.bam/ n- /mnt/scratch/users/40057929/MCL*/MCL*/12-2164*/12-2164-01_MRDneg_S1.bam/ -G /mnt/scratch/users/40057929/wg.fa/ -a svaba_Batch1_0309 -p 4
-----------------------------------------------------------
--- Running svaba SV and indel detection on 4 threads ---
---    (inspect *.log for real-time progress updates)   ---
-----------------------------------------------------------
[E::hts_open_format] fail to open file '/mnt/scratch/users/40057929/MCLHighNov2016/Batch1/04-0309-01-36351377/04-0309-01_S2.bam/'
ERROR: Cannot open main bam file: /mnt/scratch/users/40057929/MCLHighNov2016/Batch1/04-0309-01-36351377/04-0309-01_S2.bam/

I've checked the file path for the main tumour bam file and it is definitely correct. Any other advice? Let me know if you need any other information.

Thanks,
rmurphy49

**Comment by walaj** [comment]
This looks like HTSlib is having trouble with the file. Can you try samtools index on it and see if it works? It also looks like there's a trailing backlash on the file name.

**Comment by rmurphy49** [comment]
Yeah the initial issue was a syntax error with the trailing backlash. Ran it again and it flags up the following error command: svaba/bin/svaba run -t /mnt/scratch/users/40057929/MCLHighNov2016/Batch1/04-0309-01-36351377/04-0309-01_S2.bam n- /mnt/scratch/users/40057929/MCL*/MCL*/12-2164*/12-2164-01_MRDneg_S1.bam -G /users/40057929/wg.fa -a svaba_Batch1_0309 -p 4
-----------------------------------------------------------
--- Running svaba SV and indel detection on 4 threads ---
---    (inspect *.log for real-time progress updates)   ---
-----------------------------------------------------------
[E::bwa_idx_load_from_disk] fail to locate the index files
ERROR: Unable to open index file: /users/40057929/wg.fa

Again, I've checked the file path and the index file is within the same directory. Thanks for the help so far I have little experience with Linux and any help would be great.

**Comment by walaj** [comment]
Your reference genome file "wg.fa" either doesn't exist or hasn't been
indexed. You have to index the reference genome first with "bwa index" (the
same as you would if you wanted to align reads to it with BWA). This
creates some auxiliary files in the same directory that will be loaded by
SvABA / BWA.

**Comment by rmurphy49** [comment]
This is my ls command output for the working directory the reference genome file is in:

hg19bwaidx.amb
hg19bwaidx.ann
hg19bwaidx.btw
hg19bwaidx.pac
hg19bwaidx.sa
wg.fa
wg.fa.fai

Would the different indexing filenames from wg.fa be the issue?

**Comment by walaj** [comment]
Yes that's the issue

**Comment by rmurphy49** [comment]
Changed the filenames to match the indexing filenames and still nothing. Any other advice that might help? I'm going to try and build the index again from scratch in case there are any errors. The reference genome I am using (standard hg19 genome) may be different from the genome used to reference the bam files I have been provided if this may give rise to any issue, although I believe the issue I have is related the finding the files.

**Comment by walaj** [comment]
Yes, I would rebuild the reference index with "bwa index" and use that file
as the reference for SvABA. Using slightly difference reference genomes for
SvABA vs original BAM shouldn't cause a problem.

**Comment by rmurphy49** [comment]
The initial reference index was with bwa index, ran it again and still getting the same error message. All files with identical names and in the same directory. The command lines I used for bwa index were as follows:

bwa index -p hg19bwaidx -a bwtsw hg19bwaidx.fa
samtools faidx hg19bwaidx.fa

**Comment by walaj** [comment]
Is it still the "E::bwa_idx_load_from_disk" error? Could you try using the
same index and aligning using BWA-MEM? The error it is showing is from the
BWA part of the code, so that would be useful to know if that works.

**Comment by rmurphy49** [comment]
I obtained the reference fasta that was used for the alignment of the BAM file and this fixed the problem. This was also the case for other programs I am currently using which had similar issues to the one's I had described here. Thanks for the quick replies and help you have provided!
